const ApiEndpoits = {
  login: 'api/login',
  logout: 'api/logout',
  basicData: 'api/basicdata',
  getPincode: 'api/getpincode',
  getStates: 'api/getstates',
  getCities: 'api/getcities',
  getStarDetail: 'api/getStarDetail',
  offlineProfile: 'api/offlineprofile',
  checkLeadAvailableInProfileWithId: 'api/checkleadavailableinprofilewithId',
  offlineProfileSubmit: 'api/offlineprofileSubmit',
  fileUpload: 'api/fileupload',
  fileUploadDownload: 'api/fileupload/download',
  offlineSearchById: 'api/offlinesearchbyId',
  offlineRegisCallUser: 'api/offlineregiscalluser',
  offlineFetchData: 'api/offlinefetchdata',
  motherTongueList: 'api/getMothertongueList',
  saveOfflineData: 'api/saveofflinedata',
  checkLeadAvailableInProfile: 'api/checkleadavailableinprofile',
  dialerList: 'api/V1/dialerlist',
  dialerCalling: 'api/dialercalling',
  registerCheckingOffline: 'api/registercheckingoffline',
  offlineManagement: 'api/getofflinemanagement',
  offlineCallAccess: 'api/getofflinecallaccess',
  editOfflineCallAccess: 'api/editofflinecallaccess',
  offlineCallReport: 'api/getofflinecallreport',
  dataTeamReport: 'api/datateamreport',
}

export default ApiEndpoits
